### ISSUE TITLE
Decimals being cut off with number type

### ISSUE THREAD

**Issue by rileycookd** [wildseansy/sanity-plugin-computed-field#1]
First, THANK YOU! This is one of the main things Sanity was missing in my opinion.

I was playing around with the number type and it seems decimals get cut off. For example, if I console.log the result of my reduceQueryResult function I would get a number: 1036.8

However, the input would only read 1036. When I switched the input to a string it correctly displayed the decimal number in a string format.

**Comment by wildseansy** [comment]
Thanks for reporting @rileycookd. Fixed in 1.0.2
