### ISSUE TITLE
Related List

### ISSUE THREAD

**Issue by kkgthb** [wildseansy/sanity-plugin-computed-field#2]
Hey Sean, thanks for this!

Do you think you might be able to extend this, or build a similar plugin, for displaying read-only related lists using the "stack" and "card" Sanity UI elements?

It's all a little over my head, or I'd take a stab at it myself.  About as far as I can get it coming up with a GROQ query that I think exemplifies the way to get "related list" data:  `*[_type == 'person'] | order(name) { _id, name, "movies": *[_type == "movie" && references(^._id)]{title} }`.

Using the "movies" database starter from Sanity, for example, when editing Matt Damon at `http://localhost:3333/desk/person;person_matt-damon`, I'd love to, right below his picture, be able to have a little block titled "Movies" that displays a stack of cards that look kind of like Sanity's normal embedded array-of-references UI.

(Only we know that actually, in that database, Matt is a sub-property of his movies, not vice-versa -- but this helps content authors not have to think about that.)

This "input field" _(that isn't really for input at all)_ would make it look kind of like "**Interstellar**," "**The Martian**," and "**Elysium**" are sub-properties of Matt's "Movies."

One should be able to click on each movie's card in the stack and be taken to the movie detail's editing page, e.g. `http://localhost:3333/desk/movie;movie_movie_286217`.

**Comment by wildseansy** [comment]
@kkgthb - sorry for the late reply.

I think this a bit out of scope for what this is intended to do, given this is primarily intended to help CMS managers to compute values, vs. manually computing them and inputting them.

What you suggest think this is a great feature, but probably for a separate plugin or input component.  Feel free to copy this implementation to suit your needs in your case
