### ISSUE TITLE
Update for v3 ?

### ISSUE THREAD

**Issue by oliviermills** [wildseansy/sanity-plugin-computed-field#4]
Any plans to update this very useful plugin to sanity studio v3 ?

**Comment by wildseansy** [comment]
Thanks for raising concern @oliviermills. I have been out of the loop with developments in Sanity. I can take a look and see

Feel free to submit a PR if you know what needs to happen.

**Comment by wildseansy** [comment]
> Thanks for raising concern @oliviermills. I have been out of the loop with developments in Sanity. I can take a look and see
> 
> Feel free to submit a PR if you know what needs to happen.

After looking through it, it's not trivial to upgrade to v3, will take some time. Open to PRs if anyone wants to contribute

**Comment by fostimus** [comment]
I just started my sanity journey, and I'm running into many places where I need this... I'd love to contribute when I have the time and my knowledge of Sanity gets better, but wanted to echo the sentiment of needing this in v3

**Comment by wildseansy** [comment]
After doing a deep dive, I'm adding v3 support [here](https://github.com/wildseansy/sanity-plugin-computed-field/pull/5).

It will be a major version update to v2.0.0, and will have a couple of breaking changes.  See below. 

Defining a field will look like the below:


```typescript
export default defineType({
  name: 'movie',
  title: 'Movie',
  type: 'document',
  icon,
  fields: [
    {
      name: 'screeningCount',
      title: 'Screening Count',
      description: 'This represents the number of screenings of this movie',
      type: 'computedString', // Can also be 'computedNumber', 'computedText', or 'computedBoolean'
      readOnly: false, // Set to true if you don't want users to be able to toggle the computed field manually.  This replaces 'editable'
      options: {
        buttonText: 'Regenerate',
        documentQuerySelection: `
        "screeningCount": count(*[_type == "screening" && references(^._id)])
        `,
        reduceQueryResult: (result: {
          draft: {screeningCount: string}
          published: {screeningCount: string}
        }) => {
          // The result of the `reduceQueryResult` function, will supply both the result found on the draft and the published version of the document. This function can choose which to use, to reduce the result
          return result.published.screeningCount
        },
      },
    },
...
```

cc @fostimus @oliviermills

**Comment by wildseansy** [comment]
v2.0.1 is now released.  This should fix these issues for sanity v3.  See more here: https://github.com/wildseansy/sanity-plugin-computed-field#for-sanity-v3

**Comment by fostimus** [comment]
@wildseansy thank you!!
