### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by ask4clarity** [wildseansy/sanity-plugin-computed-field#6]
Hello. I successfully downloaded using

`sanity install sanity-plugin-computed-field@^1.0.2`

I am using Sanity v2. Everything compiles fine until I try to import ComputedField upon which I get this error 

```
Error in ./node_modules/sanity-plugin-computed-field/node_modules/@sanity/ui/dist/index.esm.js
Module parse failed: Unexpected token (1343:8)
You may need an appropriate loader to handle this file type.
|     if (mode === "bleed") {
|       return {
|         ...muted,
|         enabled: {
|           bg: "transparent",
 @ ./node_modules/sanity-plugin-computed-field/lib/ComputedField.js 27:13-34
 @ ./schemas/documents/product.js
 @ ./schemas/schema.js (part:@sanity/base/schema)
 @ ./node_modules/@sanity/default-layout/lib/schemaErrors/SchemaErrorReporter.js
 @ ./node_modules/@sanity/default-layout/lib/defaultLayout/DefaultLayout.js
 @ ./node_modules/@sanity/default-layout/lib/defaultLayout/index.js
 @ ./node_modules/@sanity/default-layout/lib/Root.js (part:@sanity/base/root)
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js
```

I understand if you're no longer supporting the older version but it doesn't seem to be an issue with my dependencies so I would appreciate any help. Thanks in advance.

**Comment by wildseansy** [comment]
interesting -- v1.0.2 did work in Sanity v2 at one point. It looks like this error is coming from the sanity ui library `@sanity/ui/dist/index.esm.js`.  I'm wondering if you maybe pinned your version of `@sanity/ui` lower, maybe it would work.

Unfortunately, not officially supporting v2 any longer.
