### ISSUE TITLE
feat: let the `reduceQueryResult` and `reducer` functions be async

### ISSUE THREAD

**Issue by pedropalhari** [wildseansy/sanity-plugin-computed-field#7]
## Expected Behavior
`reduceQueryResult` could accept a `async () => {}` function and wait for its completion.

## Actual Behavior
Passing `async () => {}` to `reduceQueryResult` makes the value `[object Object]`.

## Steps to Reproduce the Problem

  1. Pass any promise to `reduceQueryResult`

## Specifications

  - Version: 2.0.1

**Comment by wildseansy** [comment]
Will take a look at this week or next week. Have been busy with life changes the past couple months, sorry for the delay!

**Comment by pedropalhari** [comment]
No rush @wildseansy, the use case for this was getting the City field filled when the latitude/longitude coordinates in another field are changed.

Being async allows for an API call to Google Geolocation API to be inserted easily in the schema 🙂.
