### ISSUE TITLE
Please add `"type": "module"` to package.json

### ISSUE THREAD

**Issue by homerjam** [wildseansy/sanity-plugin-computed-field#9]
To fix `Cannot use import statement outside a module` error

Thanks :)

**Comment by wildseansy** [comment]
@homerjam - can you provide a more specific example of how you're using the plugin?  I don't think [`type: "module"` is needed in node 16+](https://stackoverflow.com/a/68558580) anymore to use the import syntax. Can you provide the node version you're using?

**Comment by wildseansy** [comment]
closing until more information is provided

**Comment by homerjam** [comment]
I finally got around to producing a minimal example and the latest release has fixed my use case, thanks!
